import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import ParentData from "./context/parentData/page";
import Navigation from "@/components/navigation/navigation";
import Parent from "./contexttt/parent/page";
import { Provider } from "react-redux";
import { store } from "@/redux/store/store";
import Providers from "@/redux/store/provider";
import ParentData from "./contextToggle/parentData/page";
import QueryProvider from "@/provider/tanstack-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <h1>hello layout</h1> */}
        {/* <Navigation/> */}
        {/* <ParentData>{children}</ParentData> */}
        {/* <Parent>{children}</Parent> */}
        {/* <Providers>{children}</Providers> */}
        <ParentData>
          <QueryProvider>
            
            {children}

          </QueryProvider>
          
          </ParentData>

        
      </body>
    </html>
  );
}
